// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbO4fMbJ9rgRrSnVKpsLaWUKc7VF8-JU0',
    appId: '1:861753072945:web:406e58ac8bf966d5282410',
    messagingSenderId: '861753072945',
    projectId: 'splitmitra-c8c3a',
    authDomain: 'splitmitra-c8c3a.firebaseapp.com',
    storageBucket: 'splitmitra-c8c3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnjYLb7niKQthnv9CeD3HX4-q15UsiZc0',
    appId: '1:861753072945:android:162fdb5d1dfb46d4282410',
    messagingSenderId: '861753072945',
    projectId: 'splitmitra-c8c3a',
    storageBucket: 'splitmitra-c8c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQyBpyUIGvU-iL2I96bqmZQXmPf3JvCM',
    appId: '1:861753072945:ios:bba9723518231817282410',
    messagingSenderId: '861753072945',
    projectId: 'splitmitra-c8c3a',
    storageBucket: 'splitmitra-c8c3a.firebasestorage.app',
    iosBundleId: 'com.example.splitmitra',
  );
}
